/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns ESP health status */
    get: operations['getEspHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a status of components connected to the ESP */
    get: operations['getEspStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pzems': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns values of all connected PZEMs */
    get: operations['getPzemValues'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pzems/address': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sets the address to PZEM */
    patch: operations['setPzemAddress'];
    trace?: never;
  };
  '/pzems/shunt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sets the shunt type to DC PZEM */
    patch: operations['setPzemShunt'];
    trace?: never;
  };
  '/pzems/counter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Resets the energy counter of all PZEMs */
    delete: operations['resetEnergyCounter'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    EspStatus: {
      wifi: components['schemas']['WiFiStatus'];
      date: components['schemas']['DateStatus'];
      pzems: components['schemas']['PzemStatus'][];
      eeprom: components['schemas']['EepromStatus'];
    };
    WiFiStatus: {
      /**
       * Format: ipv4
       * @description Station interface IP address
       */
      ip: string;
      /** @description Station interface MAC address */
      mac: string;
    };
    DateStatus: {
      /**
       * Format: date-time
       * @description UTC Date in ISO format
       */
      createdAtGmt: string;
      /**
       * Format: date-time
       * @description Date in the local timezone
       */
      createdAt: string;
    };
    PzemStatus: {
      /** @description name of PZEM sensor */
      name: string;
      /** @description true/false indicator when the PZEM is connected */
      isConnected: boolean;
      /**
       * Format: int32
       * @description Configured address to connect to the PZEM
       */
      currentAddress: number;
      /**
       * Format: int32
       * @description Address saved in PZEM memory
       */
      savedAddress: number;
      /**
       * Format: int32
       * @description Shunt type saved in PZEM memory
       */
      savedShuntType?: number;
    };
    EepromStatus: {
      /** @description true/false indicator when the EEPROM module is connected */
      isConnected: boolean;
    };
    PzemData: {
      /**
       * Format: date-time
       * @description Data collection date in UTC
       */
      createdAtGmt: string;
      pzems: components['schemas']['Pzem'][];
    };
    Pzem: {
      /** @description name of PZEM sensor */
      name: string;
      /**
       * Format: float
       * @description AC/DC voltage in Volts
       */
      voltageV?: number;
      /**
       * Format: float
       * @description AC/DC current in Amps
       */
      currentA?: number;
      /**
       * Format: float
       * @description AC/DC active power in kW
       */
      powerKw?: number;
      /**
       * Format: float
       * @description AC/DC active energy in kWh since last reset
       */
      energyKwh?: number;
      /**
       * Format: float
       * @description AC frequency in Hz
       */
      frequencyHz?: number;
      /**
       * Format: float
       * @description AC power factor of the load
       */
      powerFactor?: number;
      /**
       * Format: float
       * @description Calculated value of active energy during T1 zone
       */
      t1EnergyKwh?: number;
      /**
       * Format: float
       * @description Calculated value of active energy during T2 zone
       */
      t2EnergyKwh?: number;
    };
    PzemAddress: {
      /** @description name of PZEM sensor */
      name: string;
      /**
       * Format: int32
       * @description Address to save in PZEM memory
       */
      addressToSet: number;
      /** @description true/false indicator when the address is set */
      isChanged: boolean;
    };
    DcPzemShunt: {
      /** @description name of PZEM sensor */
      name: string;
      /**
       * Format: int32
       * @description Shunt type to save in PZEM memory
       */
      shuntTypeToSet: number;
      /** @description true/false indicator when the shunt type is set */
      isChanged: boolean;
    };
    PzemCounter: {
      /** @description name of PZEM sensor */
      name: string;
      /** @description true/false indicators for every PZEM to notify which counters were reset */
      isReset: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getEspHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  getEspStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EspStatus'];
        };
      };
    };
  };
  getPzemValues: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PzemData'];
        };
      };
    };
  };
  setPzemAddress: {
    parameters: {
      query: {
        /** @description name of the PZEM for which the address is changed */
        name: string;
        /** @description The address to set in PZEM memory */
        address: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PzemAddress'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  setPzemShunt: {
    parameters: {
      query: {
        /** @description name of the DC PZEM for which the shunt type is changed */
        name: string;
        /** @description The shunt type to set in PZEM memory */
        shunt: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DcPzemShunt'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  resetEnergyCounter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PzemCounter'][];
        };
      };
    };
  };
}
