export const ENERGY_COUNTER_T1_UA_ZONE_START_HOUR = 7;
export const ENERGY_COUNTER_T1_UA_ZONE_END_HOUR = 23;
export const ENERGY_COUNTER_T2_UA_ZONE_START_HOUR = 23;
export const ENERGY_COUNTER_T2_UA_ZONE_END_HOUR = 7;

export const TEN_MINUTES_RECORDS_AMOUNT = 600;
