/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/activate-warranty': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Warranty activate
     * @description Warranty activate
     */
    post: operations['warrantyActivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/apikeys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get apikeys
     * @description Get apikeys
     */
    get: operations['apikeysGet'];
    put?: never;
    /**
     * Add api key
     * @description Add api key
     */
    post: operations['apikeysAdd'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/apikeys/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Delete api key
     * @description Delete api key
     */
    post: operations['apikeysDelete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Auth Check
     * @description Auth Check
     */
    post: operations['authCheck'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/autotune/presets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get autotune preset list
     * @description Get autotune preset list
     */
    get: operations['autotunePresets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/autotune/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Autotune reset list of profiles
     * @description Autotune reset list of profiles
     */
    post: operations['autotuneReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/autotune/reset-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Autotune reset all profiles
     * @description Autotune reset all profiles
     */
    post: operations['autotuneResetAll'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cancel-warranty': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Warranty cancel
     * @description Warranty cancel
     */
    post: operations['warrantyCancel'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chains': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get miner chains
     * @description Get miner chains
     */
    get: operations['getChains'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chains/factory-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get miner chains factory info
     * @description Get miner chains factory info
     */
    get: operations['getChainsFactoryInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chips': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get miner chips. Deprecated. Use /chains route instead
     * @deprecated
     * @description Get miner chips. Deprecated. Use /chains route instead
     */
    get: operations['getChips'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/find-miner': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Find miner
     * @description Find miner
     */
    post: operations['findMiner'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/firmware/remove': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Remove firmware and boot from stock
     * @description Remove firmware and boot from stock
     */
    post: operations['firmwareRemove'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/firmware/update': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update firmware
     * @description Update firmware
     */
    post: operations['firmwareUpdate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get miner info
     * @description Get miner info
     */
    get: operations['getInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/layout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Layout
     * @description Layout
     */
    get: operations['layout'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lock miner
     * @description Lock miner
     */
    post: operations['lock'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lock/others': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lock other miner sessions
     * @description Lock other miner sessions
     */
    post: operations['lock_others'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/{log_type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read log file
     * @description Read log file
     */
    get: operations['logsGet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/{log_type}/clear': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear logs
     * @description Clear logs
     */
    post: operations['logsClear'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get metrics
     * @description Get metrics
     */
    get: operations['metrics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mining/pause': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mining pause
     * @description Mining pause
     */
    post: operations['miningPause'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mining/restart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mining restart
     * @description Mining restart
     */
    post: operations['miningRestart'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mining/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mining resume
     * @description Mining resume
     */
    post: operations['miningResume'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mining/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mining start
     * @description Mining start
     */
    post: operations['miningStart'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mining/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mining stop
     * @description Mining stop
     */
    post: operations['miningStop'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mining/switch-pool': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mining switch pool
     * @description Mining switch pool
     */
    post: operations['miningSwitchPool'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/perf-summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Summary
     * @description Summary
     */
    get: operations['perfSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all miner settings
     * @description Get all miner settings
     */
    get: operations['settingsGet'];
    put?: never;
    /**
     * Save miner settings
     * @description Save miner settings
     */
    post: operations['settingsSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/backup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Settings backup
     * @description Settings backup
     */
    post: operations['settingsBackup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/factory-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Settings factory reset
     * @description Settings factory reset
     */
    post: operations['settingsFactoryReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Settings restore
     * @description Settings restore
     */
    post: operations['settingsRestore'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get status
     * @description Get status
     */
    get: operations['status'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Summary
     * @description Summary
     */
    get: operations['summary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/system/reboot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * System reboot
     * @description System reboot
     */
    post: operations['systemReboot'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/unlock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Auth Check
     * @description Auth Check
     */
    post: operations['unlock'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddApiKeyRes: {
      status: components['schemas']['AddApiKeyStatus'];
    };
    /** @enum {string} */
    AddApiKeyStatus: 'inserted' | 'updated' | 'nochanges';
    AddApikeyQuery: components['schemas']['ApiKeysJsonItem'];
    AdvancedSettings: {
      asic_boost?: boolean | null;
      /** @description Disable voltage compensation feature */
      bitmain_disable_volt_comp?: boolean | null;
      disable_chain_break_protection?: boolean | null;
      disable_restart_unbalanced?: boolean | null;
      disable_volt_checks?: boolean | null;
      /** @description Automatic preset reduction in case of miner overheating or chain break error */
      downscale_preset_on_failure?: boolean | null;
      /**
       * Format: int32
       * @description Higher voltage offset during initialization stage
       */
      higher_volt_offset?: number | null;
      ignore_broken_sensors?: boolean | null;
      /** Format: int32 */
      max_restart_attempts?: number | null;
      quick_start?: boolean | null;
      quiet_mode?: boolean | null;
      remain_stopped_on_reboot?: boolean | null;
      /**
       * Format: int32
       * @description Percent, `0` to disable
       */
      restart_hashrate?: number | null;
      /** Format: int32 */
      restart_temp?: number | null;
      /**
       * Format: int32
       * @description Autotuning: hashrate threshold below which the chips are marked as bad ones
       */
      tuner_bad_chip_hr_threshold?: number | null;
    };
    AntmChain: {
      chip_statuses: components['schemas']['ChainChipStatuses'];
      chip_temp: components['schemas']['TempRange'];
      /** Format: float */
      frequency: number;
      /** Format: float */
      hashrate_ideal: number;
      /** Format: float */
      hashrate_percentage: number;
      /** Format: float */
      hashrate_rt: number;
      /** Format: float */
      hr_error: number;
      /** Format: int32 */
      hw_errors: number;
      id: number;
      pcb_temp: components['schemas']['TempRange'];
      /** Format: int32 */
      power_consumption: number;
      status: components['schemas']['ChainStatus'];
      /** Format: int32 */
      voltage: number;
    };
    AntmChainChips: {
      chips: components['schemas']['AntmChip'][];
      /** Format: float */
      freq: number;
      /** Format: float */
      hr_nominal: number;
      /** Format: float */
      hr_realtime: number;
      id: number;
      sensors: components['schemas']['AntmChipSensor'][];
      status: components['schemas']['CgChainStatus'];
    };
    AntmChainChipsStats: {
      chips: components['schemas']['AntmiChipStats'][];
      id: number;
    };
    AntmChainsChipsStats: {
      chains: components['schemas']['AntmChainChipsStats'][];
      chips_per_chain: number;
    };
    AntmChip: {
      /** Format: int32 */
      errs: number;
      /** Format: int32 */
      freq: number;
      grade: components['schemas']['ChipGrade'];
      /** Format: float */
      hr: number;
      id: number;
      /** Format: float */
      temp: number;
      /** Format: int32 */
      volt: number;
    };
    AntmChipSensor: {
      /** Format: int32 */
      board: number;
      /** Format: int32 */
      chip: number;
      /**
       * Format: int32
       * @description Location that refers to `chip.id`
       */
      loc: number;
      state: components['schemas']['TempSensorStatus'];
    };
    AntmMinerStats: {
      /**
       * Format: float
       * @deprecated
       * @description Deprecated. Same as hr_average but measure is MG/s.
       */
      average_hashrate: number;
      /** Format: int64 */
      best_share: number;
      chains: components['schemas']['AntmChain'][];
      chip_temp: components['schemas']['TempRange'];
      cooling: components['schemas']['Cooling'];
      /** Format: float */
      devfee: number;
      /** Format: float */
      devfee_percent: number;
      /** Format: int32 */
      found_blocks: number;
      /** Format: float */
      hr_average: number;
      /**
       * Format: float
       * @description Errors rate
       */
      hr_error: number;
      /** Format: float */
      hr_realtime: number;
      /** Format: float */
      hr_stock: number;
      /** Format: int32 */
      hw_errors: number;
      /** Format: float */
      hw_errors_percent: number;
      /**
       * Format: float
       * @deprecated
       * @description Deprecated. Same as hr_realtime but measure is MG/s.
       */
      instant_hashrate: number;
      miner_status: components['schemas']['MinerStatus'];
      miner_type: string;
      pcb_temp: components['schemas']['TempRange'];
      pools: components['schemas']['PoolStats'][];
      /** Format: int32 */
      power_consumption: number;
      /** Format: float */
      power_efficiency: number;
      /**
       * Format: int32
       * @deprecated
       * @description Deprecated. Same as power_efficiency
       */
      power_usage: number;
    };
    AntmiChipStats: {
      /** Format: int32 */
      errors: number;
      /** Format: int32 */
      freq: number;
      /** Format: float */
      hashrate: number;
      /** Format: int32 */
      id: number;
      sensor?: components['schemas']['TempSensor'] | null;
      status: components['schemas']['ChipGrade'];
      /** Format: float */
      temp: number;
    };
    ApiKeysJson: components['schemas']['ApiKeysJsonItem'][];
    ApiKeysJsonItem: {
      description: string;
      key: string;
    };
    Apikey: string;
    AutotuneChain: {
      chips: number[];
      /** Format: int32 */
      freq: number;
      serial?: string | null;
    };
    AutotunePresetDto: components['schemas']['AutotunePresetsItem'] & {
      tune_settings?: components['schemas']['AutotuneResultsItem'] | null;
    };
    /**
     * @description Preset status. `tuned` means that preset tuned successfully
     * @enum {string}
     */
    AutotunePresetStatus: 'untuned' | 'tuned';
    AutotunePresets: components['schemas']['AutotunePresetsItem'][];
    AutotunePresetsItem: {
      modded_psu_required: boolean;
      /** @description Preset id name */
      name: string;
      /** @description Preset human-readable name */
      pretty: string;
      status: components['schemas']['AutotunePresetStatus'];
    };
    AutotuneReset: {
      /** @description List of presets to reset */
      presets: string[];
      /** @description Restart after presets remove */
      restart: boolean;
    };
    AutotuneResetAll: {
      restart: boolean;
    };
    AutotuneResultsItem: {
      chains: components['schemas']['AutotuneChain'][];
      /** Format: int32 */
      freq: number;
      /** Format: int32 */
      hashrate: number;
      /** Format: int32 */
      volt: number;
    };
    CgChainStatus: {
      failure_message?: string | null;
      state: components['schemas']['ChainState'];
    };
    ChainChipStatuses: {
      /** Format: int32 */
      grey: number;
      /** Format: int32 */
      orange: number;
      /** Format: int32 */
      red: number;
    };
    ChainRaw: {
      /** @description An array of per chip `freq` settings values.
       *     `0` (zero) value means that value used from `chain` settings */
      chips?: number[] | null;
      /** @description Chain `disabled` settings value */
      disabled?: boolean | null;
      /**
       * Format: int32
       * @description Chain `freq` settings values.
       *     `0` (zero) value means that value used from `globals` settings
       */
      freq?: number | null;
    };
    /** @enum {string} */
    ChainState:
      | 'initializing'
      | 'mining'
      | 'stopped'
      | 'failure'
      | 'disconnected'
      | 'disabled'
      | 'unknown';
    ChainStatus: {
      description?: string | null;
      state: components['schemas']['ChainState'];
    };
    /** @enum {string} */
    ChipGrade: 'grey' | 'orange' | 'red';
    Consts: {
      cooling: components['schemas']['Cooling'];
      overclock: components['schemas']['Overclock'];
      /** @description Available timezones list.
       *     A purpose for this field is to display timezones list in UI.
       *     Makes sense for GET queries only and shall ignore for UPDATE queries. */
      timezones: (components['schemas']['Timezone'] & string)[][];
    };
    Cooling: {
      /** Format: int32 */
      fan_duty: number;
      fan_num: number;
      fans: components['schemas']['Fan'][];
      settings: components['schemas']['FanSettings'];
    };
    CoolingSettingsRaw: {
      /** Format: int32 */
      fan_min_count?: number | null;
      /** Format: int32 */
      fan_min_duty?: number | null;
      mode?: Omit<components['schemas']['ModeRaw'], 'name'> | null;
    };
    CurrentPreset: components['schemas']['AutotunePresetsItem'] & {
      globals?: components['schemas']['GlobalsRaw'] | null;
    };
    DeleteApikeyQuery: {
      key: string;
    };
    /** @enum {string} */
    DevfeeRegion: 'auto' | 'eu' | 'us' | 'cn' | 'reserve';
    DevfeeSettings: {
      region: components['schemas']['DevfeeRegion'];
    };
    DiagReportQueryInput: {
      /** @description Issue text. Max 16KB */
      issue: string;
    };
    ErrDescr: {
      err: string;
    };
    FactoryInfoChain: {
      board_model: string;
      /** Format: int32 */
      chip_bin: number;
      /** Format: int32 */
      freq: number;
      /** Format: double */
      hashrate: number;
      /** Format: int32 */
      id: number;
      serial: string;
      /** Format: int32 */
      volt: number;
    };
    FactoryInfoReply: {
      chains?: components['schemas']['FactoryInfoChain'][] | null;
      /** Format: double */
      hr_stock?: number | null;
    };
    Fan: {
      id: number;
      /** Format: int32 */
      max_rpm: number;
      /** Format: int32 */
      rpm: number;
      status: components['schemas']['FanStatus'];
    };
    /** @enum {string} */
    FanMode: 'manual' | 'immersion' | 'auto';
    FanSettings: {
      mode: {
        name: components['schemas']['FanMode'];
      };
    };
    /** @enum {string} */
    FanStatus: 'ok' | 'lost';
    FindMinerStatus: {
      /** @description Find miner on/off */
      on: boolean;
    };
    FwInfo: {
      /** @description Build time */
      build_time: string;
      /** @description Firmware name */
      fw_name: string;
      /** @description Firmware version */
      fw_version: string;
      install_type: components['schemas']['InstallType'];
      /** @description Pretty miner name */
      miner: string;
      /** @description Miner model code */
      model: string;
      platform: components['schemas']['Platform'];
    };
    GlobalsRaw: {
      /** Format: int32 */
      freq?: number | null;
      /** Format: int32 */
      volt?: number | null;
    };
    HotelFee: {
      enable: boolean;
      pool: components['schemas']['HotelFeePool'];
    };
    HotelFeePool: {
      /** Format: float */
      percent: number;
      url: string;
      worker: string;
    };
    /** @enum {string} */
    HrMeasure: 'GH/s' | 'MH/s';
    InfoJson: components['schemas']['FwInfo'] & {
      hr_measure: components['schemas']['HrMeasure'];
      serial: string;
      system?: components['schemas']['SystemInfo'] | null;
    };
    InputConfig: {
      layout?: components['schemas']['Layout'] | null;
      miner?: components['schemas']['MinerConfigRaw'] | null;
      network?: components['schemas']['InputNetworkConfFile'] | null;
      password?: components['schemas']['PasswordChange'] | null;
      regional?: components['schemas']['RegionalSettings'] | null;
      ui?: components['schemas']['UiSettings'] | null;
    };
    InputNetworkConfFile: components['schemas']['NetworkConfFile'] & {
      enable_network_check?: boolean;
    };
    /**
     * @description Install type code sd|nand
     * @enum {string}
     */
    InstallType: 'sd' | 'nand';
    Layout: {
      lg?: {
        [key: string]: string;
      } | null;
      md?: {
        [key: string]: string;
      } | null;
      sm?: {
        [key: string]: string;
      } | null;
      xs?: {
        [key: string]: string;
      } | null;
      xxs?: {
        [key: string]: string;
      } | null;
    };
    /** @enum {string} */
    Locale: 'ru' | 'en' | 'fa' | 'ua';
    /**
     * @description Log type name, `*` for all log types
     * @enum {string}
     */
    LogType:
      | 'status'
      | 'miner'
      | 'autotune'
      | 'system'
      | 'messages'
      | 'api'
      | '*';
    MetricAnnotation: {
      /** Format: int32 */
      chain_id?: number | null;
      type: components['schemas']['MinerEvent'];
    };
    MetricsData: {
      /** Format: int32 */
      chip_max_temp: number;
      /** Format: int32 */
      fan_duty: number;
      /** Format: double */
      hashrate: number;
      /** Format: int32 */
      pcb_max_temp: number;
    };
    MetricsReply: {
      annotations: components['schemas']['TimeRecordMetricAnnotation'][];
      metrics: components['schemas']['TimeRecordMetricsData'][];
      timezone: components['schemas']['Timezone'];
    };
    MinerConfigRaw: {
      cooling?: components['schemas']['CoolingSettingsRaw'] | null;
      devfee?: components['schemas']['DevfeeSettings'] | null;
      hotel_fee?: components['schemas']['HotelFee'] | null;
      misc?: components['schemas']['AdvancedSettings'] | null;
      overclock?: components['schemas']['OverclockSettingsRaw'] | null;
      pools?:
        | (components['schemas']['Pool'] &
            components['schemas']['Pool'] &
            components['schemas']['Pool'])[]
        | null;
    };
    /** @enum {string} */
    MinerEvent:
      | 'start'
      | 'stop'
      | 'restart'
      | 'reboot'
      | 'overheat'
      | 'disable_chain'
      | 'enable_chain';
    /** @enum {string} */
    MinerState:
      | 'mining'
      | 'initializing'
      | 'starting'
      | 'auto-tuning'
      | 'restarting'
      | 'shutting-down'
      | 'stopped'
      | 'failure';
    MinerStatus: {
      /** @description Optional. Description if status is failure */
      description?: string | null;
      miner_state: components['schemas']['MinerState'];
      /**
       * Format: int64
       * @description Time spent in the current state.
       *     For now implemented for `mining` state only.
       */
      miner_state_time: number;
    };
    ModeRaw:
      | {
          /** @enum {string} */
          name: 'auto';
          /** Format: int32 */
          param: number;
        }
      | {
          /** @enum {string} */
          name: 'manual';
          /** Format: int32 */
          param: number;
        }
      | {
          /** @enum {string} */
          name: 'immers';
        };
    NetworkConfFile: {
      dhcp: boolean;
      dnsservers: string[];
      gateway: string;
      hostname: string;
      ipaddress: string;
      netmask: string;
    };
    NetworkStatus: {
      dhcp?: boolean | null;
      dns: string[];
      gateway: string;
      hostname: string;
      ip: string;
      mac: string;
      netmask: string;
    };
    Overclock: {
      /** Format: int32 */
      default_freq: number;
      /** Format: int32 */
      default_voltage: number;
      /** Format: int32 */
      max_freq: number;
      /** Format: int32 */
      max_voltage: number;
      /** Format: int32 */
      max_voltage_stock_psu: number;
      /** Format: int32 */
      min_freq: number;
      /** Format: int32 */
      min_voltage: number;
      /** Format: int32 */
      warn_freq: number;
    };
    OverclockSettingsRaw: {
      chains?: components['schemas']['ChainRaw'][] | null;
      globals?: components['schemas']['GlobalsRaw'] | null;
      modded_psu?: boolean | null;
      /** @description Profile name */
      preset?: string | null;
      preset_switcher?: components['schemas']['PresetSwitcherRaw'] | null;
    };
    PasswordChange: {
      current: string;
      pw: string;
    };
    PerfSummary: {
      current_preset?: components['schemas']['CurrentPreset'] | null;
      preset_switcher: components['schemas']['PresetSwitcherRaw'];
    };
    /**
     * @description Platform type code aml|bb|cv|xil (Amlogic/BeagleBone/Cvitek/Xilix)
     * @enum {string}
     */
    Platform: 'aml' | 'bb' | 'cv' | 'xil';
    Pool: {
      pass: string;
      url: string;
      user: string;
    };
    PoolStats: {
      /** Format: int32 */
      accepted: number;
      asic_boost: boolean;
      diff: string;
      /** Format: double */
      diffa: number;
      /** Format: int32 */
      id: number;
      /** Format: float */
      ls_diff: number;
      ls_time: string;
      /** Format: int32 */
      ping: number;
      pool_type: components['schemas']['PoolType'];
      /** Format: int32 */
      rejected: number;
      /** Format: int32 */
      stale: number;
      status: components['schemas']['PoolStatus'];
      url: string;
      user: string;
    };
    /** @enum {string} */
    PoolStatus:
      | 'offline'
      | 'working'
      | 'disabled'
      | 'active'
      | 'rejecting'
      | 'unknown';
    /** @enum {string} */
    PoolType: 'UserPool' | 'DevFee' | 'HotelFee' | 'Refund';
    /** @description PresetSwitcher settings */
    PresetSwitcherRaw: {
      /** Format: int32 */
      check_time?: number | null;
      /** Format: int32 */
      decrease_temp?: number | null;
      enabled?: boolean | null;
      /** Format: int32 */
      rise_temp?: number | null;
      /** @description Profile name. Max profile that preset_switcher can switch */
      top_preset?: string | null;
    };
    RebootAfter: {
      /**
       * Format: int64
       * @description Number of seconds after the system will reboot
       */
      after: number;
    };
    RegionalSettings: {
      timezone: components['schemas']['TimezoneSettings'];
    };
    /** @description Apply config result */
    SaveConfigResult: {
      /** @description Miner restart required to apply */
      reboot_required: boolean;
      /** @description Miner restart required to apply config */
      restart_required: boolean;
    };
    /** @enum {string} */
    SchemaBoolEnum: 'true' | 'false';
    SchemaFirmwareUpdate: {
      /** Format: binary */
      file: string;
      keep_settings?: components['schemas']['SchemaBoolEnum'] | null;
    };
    SchemaSettingsRestore: {
      /** Format: binary */
      file: string;
    };
    StatusPane: components['schemas']['MinerStatus'] &
      components['schemas']['SaveConfigResult'] & {
        /** @description Flag to switch find_miner function on target devices. Optional, default `false` */
        find_miner: boolean;
        /** @description Show screen-lock status (checks that  any of auth methods satisfies) */
        unlocked: boolean;
        warranty?: components['schemas']['Warranty'];
      };
    SummaryAntmMinerStats: {
      miner?: components['schemas']['AntmMinerStats'] | null;
    };
    SwitchPoolQuery: {
      /** Format: int32 */
      pool_id: number;
    };
    SystemInfo: components['schemas']['SystemMem'] & {
      file_system_version: string;
      miner_name: string;
      network_status: components['schemas']['NetworkStatus'];
      os: string;
      uptime: string;
    };
    SystemMem: {
      /** Format: int32 */
      mem_buf: number;
      /** Format: int32 */
      mem_buf_percent: number;
      /** Format: int32 */
      mem_free: number;
      /** Format: int32 */
      mem_free_percent: number;
      /** Format: int32 */
      mem_total: number;
    };
    TempRange: {
      /** Format: int32 */
      max: number;
      /** Format: int32 */
      min: number;
    };
    TempSensor: {
      /** Format: int32 */
      chip_temp: number;
      /** Format: int32 */
      pcb_temp: number;
      status: components['schemas']['TempSensorStatus'];
    };
    /** @enum {string} */
    TempSensorStatus: 'init' | 'ready' | 'measure' | 'error' | 'unknown';
    TimeRecordMetricAnnotation: {
      data: components['schemas']['MetricAnnotation'];
      /**
       * Format: int64
       * @description UNIX time
       */
      time: number;
    };
    TimeRecordMetricsData: {
      data: components['schemas']['MetricsData'];
      /**
       * Format: int64
       * @description UNIX time
       */
      time: number;
    };
    /**
     * @description Current timezone name (code)
     * @enum {string}
     */
    Timezone:
      | 'GMT+1'
      | 'GMT+2'
      | 'GMT+3'
      | 'GMT+4'
      | 'GMT+5'
      | 'GMT+6'
      | 'GMT+7'
      | 'GMT+8'
      | 'GMT+9'
      | 'GMT+10'
      | 'GMT+11'
      | 'GMT+12'
      | 'GMT'
      | 'GMT-1'
      | 'GMT-2'
      | 'GMT-3'
      | 'GMT-4'
      | 'GMT-5'
      | 'GMT-6'
      | 'GMT-7'
      | 'GMT-8'
      | 'GMT-9'
      | 'GMT-10'
      | 'GMT-11';
    TimezoneSettings: {
      current: components['schemas']['Timezone'];
    };
    UiSettings: {
      consts?: components['schemas']['Consts'] | null;
      dark_side_pane?: boolean | null;
      disable_animation?: boolean | null;
      locale?: components['schemas']['Locale'] | null;
      theme?: components['schemas']['UiTheme'] | null;
      timezone?: components['schemas']['Timezone'] | null;
    };
    /** @enum {string} */
    UiTheme: 'light' | 'dark' | 'auto';
    UnlockScreenBody: {
      /** @description Target device(s) password */
      pw: string;
    };
    UnlockSuccess: {
      token: string;
    };
    ViewConfig: {
      layout?: components['schemas']['Layout'] | null;
      miner: components['schemas']['MinerConfigRaw'];
      network: components['schemas']['NetworkConfFile'];
      password?: components['schemas']['PasswordChange'] | null;
      regional: components['schemas']['RegionalSettings'];
      ui: components['schemas']['UiSettings'];
    };
    /** @enum {string} */
    Warranty: 'active' | 'inactive' | 'expired' | 'cancelled' | 'not_provided';
    WarrantyStatus: {
      success: boolean;
      warranty?: components['schemas']['Warranty'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  warrantyActivate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Warranty was successfully activated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WarrantyStatus'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  apikeysGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Api key list read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiKeysJsonItem'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Key delete error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  apikeysAdd: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddApikeyQuery'];
      };
    };
    responses: {
      /** @description Api key was added successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddApiKeyRes'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  apikeysDelete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteApikeyQuery'];
      };
    };
    responses: {
      /** @description Key deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Key delete error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  authCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  autotunePresets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Autotune preset list read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AutotunePresetDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  autotuneReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AutotuneReset'];
      };
    };
    responses: {
      /** @description Reset list of autotune profiles done successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  autotuneResetAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AutotuneResetAll'];
      };
    };
    responses: {
      /** @description Reset all autotune profiles done successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  warrantyCancel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Warranty canceled successfully, or was not provided */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WarrantyStatus'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  getChains: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chains read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AntmChainChips'][];
        };
      };
    };
  };
  getChainsFactoryInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chains factory info read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactoryInfoReply'];
        };
      };
    };
  };
  getChips: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chips read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AntmChainsChipsStats'];
        };
      };
    };
  };
  findMiner: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request handled successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FindMinerStatus'] | null;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  firmwareRemove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Firmware was successfully removed. System will reboot after */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RebootAfter'];
        };
      };
      /** @description This model has no 'remove firmware' */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Firmware remove error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  firmwareUpdate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['SchemaFirmwareUpdate'];
      };
    };
    responses: {
      /** @description Firmware update successfully. System will reboot after */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RebootAfter'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Firmware update error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  getInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Miner Info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InfoJson'];
        };
      };
    };
  };
  layout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dashboard elements layout */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Layout'] | null;
        };
      };
    };
  };
  lock: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session dropped */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lock_others: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UnlockScreenBody'];
      };
    };
    responses: {
      /** @description Other sessions dropped */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Wrong password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logsGet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Log type name. All logs `*` are not implemented for this route */
        log_type: components['schemas']['LogType'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Log file was read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Clean logs error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  logsClear: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Log type */
        log_type: components['schemas']['LogType'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logs was cleared successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Clean logs error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  metrics: {
    parameters: {
      query: {
        /** @description Amount of seconds until now. Max is 3 days (3 * 24 * 60 * 60) Default is 1 day (24 * 60 * 60) */
        time_slice: number;
        /** @description Resample step in seconds to count average, default is 15 min (15 * 60) */
        step: number;
        /** @description Pet id */
        until: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Config saved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetricsReply'];
        };
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  miningPause: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Mining paused */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Mining pause error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  miningRestart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Mining restart */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Mining restart error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  miningResume: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Mining resumed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Mining resume error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  miningStart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Mining started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Mining start error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  miningStop: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Mining stopped */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Mining stop error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  miningSwitchPool: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SwitchPoolQuery'];
      };
    };
    responses: {
      /** @description Pool was switched successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Mining switch-pool error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  perfSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chips read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PerfSummary'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  settingsGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Config read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ViewConfig'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config read error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  settingsSave: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InputConfig'];
      };
    };
    responses: {
      /** @description Config saved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SaveConfigResult'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Config save error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  settingsBackup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backup binary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  settingsFactoryReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Settings factory reset done successfully. System will reboot after */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RebootAfter'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  settingsRestore: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['SchemaSettingsRestore'];
      };
    };
    responses: {
      /** @description Firmware restored successfully. System will reboot after */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RebootAfter'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Miner have warranty. Cancel warranty first */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusPane'];
        };
      };
    };
  };
  summary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Summary read successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SummaryAntmMinerStats'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrDescr'];
        };
      };
    };
  };
  systemReboot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description System reboot after */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RebootAfter'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  unlock: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UnlockScreenBody'];
      };
    };
    responses: {
      /** @description Authorized */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnlockSuccess'];
        };
      };
      /** @description Wrong password */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
