/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns ESP health status */
    get: operations['getEspHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a status of components connected to the ESP */
    get: operations['getEspStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sensors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns values of all connected sensors */
    get: operations['getSensorsValues'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/protection-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns values of all registered protection rules */
    get: operations['getProtectionRules'];
    /** Save protection rule */
    put: operations['saveProtectionRule'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pzems/address': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sets the address to PZEM */
    patch: operations['setPzemAddress'];
    trace?: never;
  };
  '/pzems/counter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Resets the energy counter of all PZEMs */
    delete: operations['resetEnergyCounter'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/relays': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a status of connected relay */
    get: operations['getRelayStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/relays/on': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Turns relay ON and returns status */
    post: operations['turnRelayOn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/relays/off': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Turns relay OFF and returns status */
    post: operations['turnRelayOff'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/relays/toggle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Inverts relay state and returns status */
    post: operations['toggleRelay'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    EspStatus: {
      wifi: components['schemas']['WiFiStatus'];
      date: components['schemas']['DateStatus'];
      pzems: components['schemas']['PzemStatus'][];
      eeprom: components['schemas']['EepromStatus'];
    };
    WiFiStatus: {
      /**
       * Format: ipv4
       * @description Station interface IP address
       */
      ip: string;
      /** @description Station interface MAC address */
      mac: string;
    };
    DateStatus: {
      /**
       * Format: date-time
       * @description UTC Date in ISO format
       */
      createdAtGmt: string;
      /**
       * Format: date-time
       * @description Date in the local timezone
       */
      createdAt: string;
    };
    PzemStatus: {
      /** @description The name of the PZEM sensor */
      name: string;
      /** @description true/false indicator when the PZEM is connected */
      isConnected: boolean;
      /**
       * Format: int32
       * @description Configured address to connect to the PZEM
       */
      currentAddress: number;
      /**
       * Format: int32
       * @description Address saved in PZEM memory
       */
      savedAddress: number;
      /** @description true/false indicator to include reactive power param into calculation */
      isFullPower?: boolean;
    };
    EepromStatus: {
      /** @description true/false indicator when the EEPROM module is connected */
      isConnected: boolean;
    };
    SensorsData: {
      /**
       * Format: date-time
       * @description Data collection date in UTC
       */
      createdAt: string;
      /** @description Status of the power relay */
      power: boolean;
      sensors: components['schemas']['Sensor'][];
      /** @description Indicator to point whether protection has been triggered */
      pTriggered: boolean;
    };
    Sensor: {
      /** @description The name of the sensor */
      name?: string;
      /**
       * Format: float
       * @description AC/DC voltage in Volts
       */
      voltage?: number;
      /**
       * Format: float
       * @description AC/DC average voltage in Volts
       */
      avgVoltage?: number;
      /**
       * Format: float
       * @description AC/DC current in Amps
       */
      current?: number;
      /**
       * Format: float
       * @description AC/DC active power in kW
       */
      power?: number;
      /**
       * Format: float
       * @description AC/DC active energy in kWh since last reset
       */
      energy?: number;
      /**
       * Format: float
       * @description AC frequency in Hz
       */
      frequency?: number;
      /**
       * Format: float
       * @description AC power factor of the load
       */
      powerFactor?: number;
      /**
       * Format: float
       * @description Calculated value of active energy during T1 zone
       */
      t1Energy?: number;
      /**
       * Format: float
       * @description Calculated value of active energy during T2 zone
       */
      t2Energy?: number;
      /** @description Object with registered protection rules */
      protection?: {
        [key: string]: boolean;
      };
    };
    ProtectionRule: {
      /** @description The id of the protection rule */
      id: string;
      /** @description Min value of rule */
      min: number;
      /** @description Max value of rule */
      max: number;
    };
    PzemAddress: {
      /** @description The name of the PZEM sensor */
      name: string;
      /**
       * Format: int32
       * @description Address to save in PZEM memory
       */
      addressToSet: number;
      /** @description true/false indicator when the address is set */
      isChanged: boolean;
    };
    PzemCounter: {
      /** @description The name of the PZEM sensor */
      name: string;
      /** @description true/false indicators for every PZEM to notify which counters were reset */
      isReset: boolean;
    };
    RelayStatus: {
      /** @description Current status of the relay */
      status: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getEspHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  getEspStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EspStatus'];
        };
      };
    };
  };
  getSensorsValues: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SensorsData'];
        };
      };
    };
  };
  getProtectionRules: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProtectionRule'][];
        };
      };
    };
  };
  saveProtectionRule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ProtectionRule'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  setPzemAddress: {
    parameters: {
      query: {
        /** @description The name of the PZEM for which the address is changed */
        name: string;
        /** @description The address to set in PZEM memory */
        address: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PzemAddress'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  resetEnergyCounter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PzemCounter'][];
        };
      };
    };
  };
  getRelayStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RelayStatus'];
        };
      };
    };
  };
  turnRelayOn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RelayStatus'];
        };
      };
    };
  };
  turnRelayOff: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RelayStatus'];
        };
      };
    };
  };
  toggleRelay: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RelayStatus'];
        };
      };
    };
  };
}
